### PR TITLE
Remove iFrame logic along with publicConfig

### PR DESCRIPTION
**Pull request by andrepimenta**
This PR removes iFrame logic along with publicConfig.

### CODE REVIEW

**Review by rekmarks — CHANGES_REQUESTED** [review]
If you search all files for `publicConfig`, there's more code to remove in `setProvider.js` and `inpage.js`.

**Comment by rekmarks** [comment]
Don't bother with `setProvider.js`, which is removed entirely in: #42

**Comment by rekmarks** [comment]
The only remaining `publicConfigStore` reference we care about is in `inpage/index.js`.

**Comment by andrepimenta** [comment]
> The only remaining `publicConfigStore` reference we care about is in `inpage/index.js`.

Should be good now!

**Review by rekmarks — APPROVED** [review]

**Pull request merged**
